version: '3'

services:
  # Kerberos Server (KDC)
  kerberos-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: kerberos.example.com

  # Kerberos Client (for manual checks)
  kerberos-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: tail -f /dev/null # keep container running